version: '3.2'

services:
   db:
      image: mysql
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root

   phpmyadmin:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
   app_api:
    image: "my_backend" 
    build: .
    ports:
      - "30030:3000"
    restart: always
    depends_on:
      - db